parameters:
    tos.agreement.class: LoginCidadao\TOSBundle\Entity\Agreement
    tos.terms_of_service.class: LoginCidadao\TOSBundle\Entity\TermsOfService

    tos.manager.class: LoginCidadao\TOSBundle\Model\TOSManager
    tos.agreement.listener.class: LoginCidadao\TOSBundle\EventListener\CheckAgreementListener

    tos.user_register.listener.class: LoginCidadao\TOSBundle\EventListener\RegistrationSubscriber

services:
    tos.terms_of_service.repository:
        class: %tos.terms_of_service.class%
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - %tos.terms_of_service.class%

    tos.agreement.repository:
        class: %tos.agreement.class%
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - %tos.agreement.class%

    tos.manager:
        class: %tos.manager.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@tos.agreement.repository"
            - "@tos.terms_of_service.repository"

    tos.agreement.listener:
        class: %tos.agreement.listener.class%
        arguments:
            - "@security.authorization_checker"
            - "@security.token_storage"
            - "@tos.manager"
            - "@security.http_utils"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onFilterController }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    tos.user_register.listener:
        class: %tos.user_register.listener.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@tos.manager"
        tags:
            - { name: kernel.event_subscriber }

    tos.markdown.parser.standard:
        class: cebe\markdown\Markdown
        arguments: ~

    tos.markdown.parser.github:
        class: cebe\markdown\GithubMarkdown
        arguments: ~

    tos.twig.markdown_extension:
        class: LoginCidadao\TOSBundle\Twig\Extension\MarkdownExtension
        arguments:
            - "@tos.markdown.parser.standard"
        tags:
            - { name: twig.extension }
